### ISSUE TITLE
Is the function call hanging the best possible format?

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#123]
The function call hanging implemented in v0.7.0 helps to improve readability for longer chains, however, some places don't look as great.

We follow the heuristic that we only hang method calls, not static functions. i.e., StyLua would hang as such:
```lua
Promise.new(...)
    :andThen(...)
    :catch(...)
```

However, some APIs don't use a static `.new()` method to create a new object, and may use a `:new()` instead. But StyLua would format it as such:
```lua
FooBar
    :new(...)
    :process(...)
```
But, would it be better for it to be like below?
```lua
FooBar:new(...)
    :process(...)
```
If we were to do this, what kind of heuristic would we have to apply?
Prettier also has a [similar problem](https://youtu.be/0Q4kUNx85_4?t=967). The heuristic they implement is to determine if the first identifier (the prefix in the AST) is uppercase. (e.g. `Object.keys()` and `Promise.new()` vs. `items.filter()`)

A similar heuristic is also implemented for JavaScript `this`. Should we do the same here for `self`?
```lua
self
    :GetOwnedVehicles()
    :andThen(...)
    :catch(...)
```
vs.
```lua
self:GetOwnedVehicles()
    :andThen(...)
    :catch(...)
```

Are there any other places where it looks weird?

**Comment by LastTalon** [comment]
At first glance I would simply say never to hang the first call in a sequence of function calls based purely on non-semantic differences. I think that makes it flow and read appropriately in all of these cases.

I can't think of many places I would desire to break that rule. Even for long function or variable names with the first call I don't think I would want it hanging.

```lua
aVeryLongVariableName.withAVeryExtremelyLongNoGoodFunctionCallName()
```
still seems better to me than
```lua
aVeryLongVariableName
    .withAVeryExtremelyLongNoGoodFunctionCallName()
```
when its the first function being called as a member of that variable.

The clarity of hanging the function calls comes from the them being sequenced similar to items in a multi-line table or function call. So the benefit of hanging the first really only exists in the context of multiple subsequent function calls in my opinion.

```lua
self:first()
    :second()
    :third()
```
is useful for the same reason as
```lua
self = {
    "first",
    "second",
    "third",
}
```
and likewise the usefulness of this formatting is sort of proportional to the length of the list. So for the first term hanging, the benefit is sort of negligible.

That I think allows us to focus more on the semantic aspect of when to hang them or not. This is where I think the core of the issue is.

As you point out, using `:` as part of the heuristic can cause problems because we don't know how an API is going to treat its member functions, whether as static or methods. You point out `new` which for many is static, but for some is a method. This also can go the other way as well, where lots of functions typically called can be static functions.

```lua
Object.first()
    .second()
    .third()
```
can still be a valid call chain and we don't necessarily know the library's implementation or semantics here.

The capitalization heuristic could be useful, but I sense still has problems. I think the issue comes from the intentionality of the programmer, rather than the semantics of the code here.

Consider two classes of function calls being chained.
```lua
items:modify()
    :andThen()
    :catch()
```
gets turned into
```lua
items
    :modify()
    :andThen()
    :catch()
```
The programmer says he doesn't like that because the promise is the thing he wanted to hang. This is very similar to the reasoning behind using the capitalization heuristic.
```lua
Object.keys()
    .map()
    .filter()
```
but it leaves us with the same problem.

The reason for this is not simply because of a semantic difference between them, but because of the intentionality of the programmer to differentiate these semantics using that formatting. You could get the same case, but far more egregious.

```lua
items
    :prune()
    :simplify()
    :modify()
    :andThen()
    :catch()
```
only here we can see that these two lists of function calls don't really belong in the same chain even though they're being used that way.

This makes it more apparent I think that this style is probably used more to differentiate two separate types of function calls. Unfortunately, people do chain calls this way and we can't know these semantics or the intentionality of the programmer here.

That's just my two cents on the underlying issue we're looking at here. I'm sort of split in my thinking on whether to use the capitalization heuristic or not though.

**Comment by JohnnyMorganz** [comment]
The main reason against always leaving the first call on the same line, is it makes the indentation odd for cases where the arguments are anonymous functions, such as `:andThen()` and `:catch()`:
```lua
somePromise:andThen(function()
    local x = 1
    local foo = "bar"
    return true
end)
    :catch(function()
        local err = foobar
        print(err)
    end)
    :finally(function()
        doCleanup(someArg)
    end)
```
The way the alignment differs looks odd, as compared to:
```lua
somePromise
    :andThen(function()
        local x = 1
        local foo = "bar"
        return true
    end)
    :catch(function()
        local err = foobar
        print(err)
    end)
    :finally(function()
        doCleanup(someArg)
    end)
```
I'm reluctant to change this current behaviour.

Hanging a chain of static methods is also a valid point, although in practice, how likely is this? I thought it was unlikely that a static chain would happen, since they normally don't act on a specific object - the exception being `.new()` which instantiates the object.
If its more common than I anticipated, it would probably be wise to include static methods in the hanging chain list.

I also agree with the semantics point, as sometimes the programmer may want to hang in different places as the calls represent different things. Its definitely a tricky one. I think a good reference point here is to replicate what prettier does, and the heuristics it employs, as the style its enforcing is used in many projects, and the JavaScript syntax is similar to Lua in this regard.
It is likely that it may not always be the style that a specific programmer would want, but I think it is reasonable to compromise here.

**Comment by LastTalon** [comment]
You're definitely correct where the arguments are anonymous functions. I hadn't considered it. But not only that, I would say that's the case for all functions with multi-line arguments, not just the anonymous functions. That's something that can at least be handled without trying to analyze the semantics though.

I have no idea how frequently chains of static methods will pop up and I think that's exactly the problem with it. Some library could do it and it would be a problem to base any formatting on the assumed semantics if they do. We simply don't know, so I'd just say treat it exactly the same as member functions.

I think the compromise is appropriate as long as its not going to cause problems if the heuristic doesn't apply in some case (which I don't think it does). Its better to make some parts formatted nicer even if we can't do it everywhere so long as that doesn't cause drastic inconsistency.

**Comment by JohnnyMorganz** [comment]
Closing this issue as there hasn't been any further comments about it. I think the current style is OK to stick with for now.
If anybody is seeing this, I'm happy to reopen this discussion if anybody would like to.
