### ISSUE TITLE
Allow checking that files are already formatted

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#14]
This would be similar to `prettier --check` (prettier also uses `prettier --write` when formatting the files to distinguish) and would allow quick checks that the project is already compliant with the formatting created by StyLua. This can help with CI checks to ensure everyone is using StyLua in their contributions easily.

**Comment by JohnnyMorganz** [comment]
This should be completed as of https://github.com/JohnnyMorganz/StyLua/commit/ea402edb018e1470604042431e6cd4f337efbb8b

StyLua now accepts the `--check` flag. When using this, StyLua will search through files as it normally would, but instead of overwriting the file contents with the formatted version, StyLua will output a diff. If there are some files which aren't fully formatted, StyLua will exit with status code 1 - which can be used for CI checks.
