### ISSUE TITLE
Spaces as default or global config

### ISSUE THREAD

**Issue by tiagovla** [JohnnyMorganz/StyLua#146]
So far, the transition from **lua-format** to **stylua** was flawless. 

My only issue is that I need to configure it for every project because it uses tabs as default, unlike **lua-format**. Is there a particular reason for that? 

It would be nice if it would:

1. search for local config
2. fallback to global config (maybe inside ~/.config/stylua.toml)
3. fallback to default config

**Comment by JohnnyMorganz** [comment]
It's great to hear that the transition went smooth!
> it uses tabs as default, unlike **lua-format**. Is there a particular reason for that? 

StyLua is designed around the following style guide: https://roblox.github.io/lua-style-guide/, in which case Tabs are set to default. It is unlikely that will change.

> fallback to global config (maybe inside ~/.config/stylua.toml)

I'm against this behaviour for the same reasons I described in
https://github.com/JohnnyMorganz/StyLua/issues/127#issuecomment-828390911 - if you are working with other developers for a repo and it uses default StyLua (no config file in project), and you change from the default config in a parent/global config, then the changed config you applied would be used, rather than the formatting for the project, which is unwanted.
One thing I could do, however, is to introduce a CLI flag e.g. `--search-parent-directories` or similar. In this case, we would look for the config in a parent directory, or in the e.g. XDG_CONFIG_HOME. This will provide the functionality you want, whilst keeping the original behaviour as default. How does that sound?

**Comment by tiagovla** [comment]
Great!

**Comment by matu3ba** [comment]
@JohnnyMorganz I want to point out that the guide is underspecified, as it does [not define the tab length](https://roblox.github.io/lua-style-guide/#general-whitespace) and rather make rules based on assumptions.
Further I would have expected from the guide to take into consideration that tab settings are an additional and inconsistent editor configuration.

If you want to have some [glory editor examples not a tab width of 4](https://github.com/eclipse/wildwebdeveloper/issues/457) [here](https://superuser.com/questions/355863/why-is-the-default-tab-size-8-spaces-where-does-this-come-from-and-why-is-it-th).

And this does not even take into consideration [other messed up technology having different tab-length or requiring explicit configuration](https://meta.stackexchange.com/questions/234784/please-set-the-editor-tab-size-to-4).

**Comment by JohnnyMorganz** [comment]
StyLua uses `indent_width` as the definition of a single tab width, and a single tab is used per indentation. 

I'm not sure what the guide states specifically, it is the inspiration for this formatter, but not necessarily the defining specification.

I think, to not get into a debate about tabs vs spaces, the option is open for configuration for a project, they don't need to force tabs if they don't want it. Personally, tabs are important to me for [accessibility reasons](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/?utm_source=amp&utm_medium=&utm_content=post_body)
