### ISSUE TITLE
File globs overridden in .styluaignore by command line globs argument

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#18]
When adding something such as `*.spec.lua` to .styluaignore then running `stylua --check .` a diff is produced for `*.spec.lua` files.

Possibly related to #20.

**Comment by JohnnyMorganz** [comment]
I think the issue here is that the [ignore](https://docs.rs/ignore/0.4.17/ignore) crate which I use won't honour .styluaignore files if a glob pattern matches. By default, we set the whitelist glob pattern to `**/*.lua`, and since this has higher precedence than the globs in `.styluaignore` (i.e. adding in `*.spec.lua`), then it isn't ignored.

I currently can't think of a way to work around this, other than removing the `**/*.lua` default glob pattern, and maybe using a [file type](https://docs.rs/ignore/0.4.17/ignore/types/index.html) matcher instead - that would probably mean creating a new CLI argument

**Comment by LastTalon** [comment]
There's possibly a related bug in #20 where the command line multiple glob matching seems to be messing up as well for this kind of thing.
