### ISSUE TITLE
Table with multiline fields should always expand

### ISSUE THREAD

**Issue by ktrz** [JohnnyMorganz/StyLua#187]
I'm using the latest trunk version as of June 15
The formatted output differs for the same code but with a single newline difference

```
local obj = { method1 = function(self) end, method2 = function(self, name) end }
``` 
results in 

```
local obj = { method1 = function(self)
end, method2 = function(self, name)
end }
```

---
and

```
local obj = {
    method1 = function(self) end, method2 = function(self, name) end }
```

results in

```
local obj = {
	method1 = function(self)
	end,
	method2 = function(self, name)
	end,
}
```

I assume that the latter is the correct behavior.

**Comment by JohnnyMorganz** [comment]
This table expansion is actually expected behaviour. It's an idea we take from prettier, which you can read more about
[here](https://prettier.io/docs/en/rationale.html#multi-line-objects) if you want.
Essentially, there are cases where you *want* tables to be multi line (e.g. config, object declaration, etc.) so if StyLua/prettier finds a newline after the opening brace, we automatically expand (and keep) it multi line.

As your example shows though, this does have a bit of an issue. The formatting is not reversible - if the table expands (i.e. it became too long or you explicitly put a newline), it will never collapse again, even if it's small enough, until you remove the newline. 
Currently there isn't really a good heuristic to keep the best of both worlds

---

Having said this, there is something we could improve here. It would be good if an anonymous function with no body stays on a single line, so that we actually keep what you started with (if it's under the column width)

**Comment by ktrz** [comment]
Thank you for the quick response

We are actually having a longer example with multiple properties. And even though the length indicates that it should be broken down it behaves weirdly

```
local obj = { method1 = function(self) end, method2 = function(self, name) end, method3 = function(self) end, method4 = function(self, name) end, ["some-method"] = function(self) end, ["another-method"] = function(self, name) end, ["some-another-method"] = function(self) end, ["yet-another-method"] = function(self, name) end }
```

This one line is formatted like this

```
local obj = { method1 = function(self)
end, method2 = function(self, name)
end, method3 = function(self)
end, method4 = function(self, name)
end, ["some-method"] = function(self)
end, ["another-method"] = function(self, name)
end, ["some-another-method"] = function(self)
end, ["yet-another-method"] = function(self, name)
end }
```

Wouldn't it make sense to expand the table at this point?

**Comment by JohnnyMorganz** [comment]
The table should definitely be expanded here, I agree.
I think this ties in above with having the anonymous functions stay on a single line (no newline between parameters and end). Because they are being split here, they all *technically* fit under the column width, which is why its accepted as such, but this format isn't great.
