### ISSUE TITLE
Attempting to match globs finds no files

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#20]
Using the example in the readme for avoiding matching `.spec.lua` files or modified ones like `stylua -g **/*.lua -g !**/*.spec.lua .` just returns `error: no files provided`. Ideally this should match against regular `.lua` files that are discoverable in the path given.

This seems to be related to the glob option matching multiple patterns following it and the path to run on being treated as a glob. `stylua -g **/*.lua .` has this problem, but `stylua -g **/*.lua --check .` does not.

**Comment by JohnnyMorganz** [comment]
The problem here indeed is that when you use the glob argument, since it can match multiple strings, it takes your files argument as another glob, rather than actually as files.
If you check out `stylua --help`, you will see that the optional `--` argument can be used to separate the arguments and the files.
The following won't work:
```
stylua -g *.lua .
```
But this will:
```
stylua -g *.lua -- .
```

I will update the README with this!

**Comment by JohnnyMorganz** [comment]
I've added this into the README as of https://github.com/JohnnyMorganz/StyLua/commit/da106f3035fcb4556c9f00a67403e68970f632c3
