### ISSUE TITLE
inlines conditional chain to one line, even when comment is on last link in the chain

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#204]
```
local isValid =
        -- Allow nil for cond decl
        contextType == nil or
          (ctxType["$$lulz"] === CTX_TYPE and
          ctxType.__real__ ==nil) -- Not a <Ctx.Consummate>
```

becomes
```
local isValid =
        -- Allow nil for cond decl
        contextType == nil or (ctxType["$$lulz"] === CTX_TYPE and ctxType.__real__ ==nil) -- Not a <Ctx.Consummate>
```

making the comment only meant for the last line in the conditional no longer make sense. When we see a comment on any part of a conditional chain or argument list, including the last one, it should hang (or maintain existing whitepace) on each link in the chain. This appears to be what prettier 2.x does.

**Comment by JohnnyMorganz** [comment]
We discussed this some days ago on Discord - the prettier heuristic was that it just buffers comments until it can find the first place to put them [i.e. a line break], and the reason its different in prettier vs. stylua is the column width difference (setting column width to `80` would lead to the original input).

> When we see a comment on any part of a conditional chain or argument list, including the last one, it should hang (or maintain existing whitepace) on each link in the chain

This is difficult to do when the comment is at the end of the chain/expression, because there are cases where the comment isn't just relevant to the last part of the chain, it might just be for the whole expression. In that case, we don't really want to maintain whitespace/hang unnecessarily, as it doesn't make sense and we are under the width.
If we hang depending on the existing whitespace, then there also because the issue again of formatting reversibility: imagine if this is originally on one line as you show on the output, and you come to edit it to add another condition in the middle, by firstly starting a new line. But, you decide that you no longer want the condition anymore, and delete it but don't delete the newline you added. When running the formatter again, we will now hang, leading to an unnecessary diff as there was no code change.

I'm not entirely sure on a good heuristic to apply in this scenario to keep the logic you want to have, whilst also respecting the two points above.

**Comment by JohnnyMorganz** [comment]
I'm going to close this because I think what we have right now is OK, and as mentioned earlier the style in OP has some issues.
I'm happy to reopen this though if you have any other thoughts about it.
