### ISSUE TITLE
Indenting on ':' syntax

### ISSUE THREAD

**Issue by levouh** [JohnnyMorganz/StyLua#235]
The original text looks like:

![image](https://user-images.githubusercontent.com/31262046/126926315-04b057b8-4106-4d22-b9e6-96fa0f1ba1c4.png)

and after formatting:

![image](https://user-images.githubusercontent.com/31262046/126926343-44ea6b0f-af34-49c0-8c10-41e8d7bcc2a9.png)

which does not appear intentional based on the behavior in other places. Anything else I can post to help debug this (if it is indeed a bug)?

**Comment by JohnnyMorganz** [comment]
This actually is intentional - it was introduced in https://github.com/JohnnyMorganz/StyLua/issues/109

I did open https://github.com/JohnnyMorganz/StyLua/issues/123 discussing about this and anything that should be changed, but it had no movement so I let it be.

A similar formatting style can be found when using prettier and JavaScript/TypeScript

Is there something you would like to see different in the current style?

**Comment by levouh** [comment]
The example(s) on #109/#123 make sense, and I understand that there is an explicit reservation here to be opinionated as well. Have you considered adding an option to disable this hanging completely? Before creating this issue I was appalled by the idea of it, but it has actually grown on me in the last 11 hours :wink:

**Comment by JohnnyMorganz** [comment]
I appreciate the different style choices, but I'm always very hesitant about adding new options. `no_call_parentheses` was added for adoptability mainly, but I imagine it will probably be the last option that will be added anytime soon.

That said, I'm happy to change the current style output though if there's something which people think might look better.
(I do need to start being more wary of radically changing styles though as the formatter is getting more widely used, since it can lead to big diffs)

**Comment by levouh** [comment]
Nah I think that the way it is setup right now is fine, and makes sense when things are chained together like you've noted with the _Prettier_ example, etc. The less options, the better.
