### ISSUE TITLE
Allow blank comments on the same line as end of multiline comments

### ISSUE THREAD

**Issue by OttoHatt** [JohnnyMorganz/StyLua#238]
I've seen this used somewhat often as a neat separator in large files, however formatting puts the separator on a new line:

Before formatting:
![image](https://user-images.githubusercontent.com/68089630/128445268-b5990d3e-466c-4285-9f2a-691134cbb488.png)
After formatting:
![image](https://user-images.githubusercontent.com/68089630/128445297-7b438223-0d74-43d7-b2ba-7001d9e02671.png)

Maybe there should be an exception for blank comments (separators?). Since I can definitely see the use case in formatting normal comments with new lines.

**Comment by JohnnyMorganz** [comment]
I'm a bit wary about adding such a specific style choice like this. It seems only useful for this specific case.

If you swapped it around so that it was `------]]--`, then it would format on a single line, but I understand if that isn't something you would want.

I can think about it, but currently it seems unlikely.

**Comment by Joakker** [comment]
Why not do something like
```lua
--[=================================[
--       My super cool file
--]=================================]
```

**Comment by JohnnyMorganz** [comment]
I'm going to close this because I don't think I'll add a special case for this.
However, if you disagree and think it should be handled, let me know
