### ISSUE TITLE
Comment indentation for elseif condition

### ISSUE THREAD

**Issue by Dionysusnu** [JohnnyMorganz/StyLua#254]
The following snippet creates a weird formatting result. It retains the empty line whitespace, but still indents the comment for the next condition:
```lua
if condition1 then
	print("Do something")

--[[
	my multiline comment
]]
elseif condition2 then
	print("Do something else")

-- my single line comment
elseif condition3 then
	print("Do some final thing")
end
```

If there are empty lines before the comments, like here, this should be considered a comment on the elseif condition, and therefore not indented.

**Comment by Dionysusnu** [comment]
> Are you referring to the indentation _inside_ the multi line comment? Since both the comments look aligned with the else if.
> 
> If it's the text inside the multi line you're talking about, StyLua doesn't touch what's inside a comment at all. If the brackets indentation is reduced, we don't also reduce it inside the comment, as we can't tell whether it's intended or not.
Sorry, that was my mistake, this is the _input_ code. StyLua formats it as:
```lua
if condition1 then
	print("Do something")

	--[[
	my multiline comment
]]
elseif condition2 then
	print("Do something else")

	-- my single line comment
elseif condition3 then
	print("Do some final thing")
end
```
which looks quite odd

**Comment by JohnnyMorganz** [comment]
Hm, this is a tricky one.
How can we tell if a comment is intended for the if-block, or leading the elseif/else condition. You mention that we should use the heuristic of checking if there is an empty newline before the comment - sounds OK, just wondering if there's any cases where this may not be good.

The reason why this isn't as easy is because of e.g. something like
```lua
if foo then
    -- TODO: complete this
elseif bar then
    print("x")
end
```
the comment is for the block, not the condition. In this case, the heuristic you mention does work, but is it always the correct heuristic?

**Comment by JohnnyMorganz** [comment]
Was looking at this again. The two ideas I come up with were the following:
1) Apply the following heuristic: if the body has no content (other than the comment), we indent the comment. Otherwise, we say the comment is leading the else-if condition

2) Rely on the initial indentation of the comment. If it was indented one level further, we will keep it one level further.

If 1. covers most, if not all, cases, I would rather go down that route than relying on the input formatting

**Comment by JohnnyMorganz** [comment]
@matthargett pointed out that this is causing issues in their code base.
May need to revert this change
