### ISSUE TITLE
Remove extra indentation of parentheses, similar to tables/function calls

### ISSUE THREAD

**Issue by archiif** [JohnnyMorganz/StyLua#274]
Stuff enclosed in parentheses seems to have an inconsistent indentation style.
Instead of looking like this:
```lua
local tbl = {
    key = long_variable_name,
    key = long_variable_name,
    key = long_variable_name,
    key = long_variable_name,
}
function_call(
    long_variable_name,
    long_variable_name,
    long_variable_name,
    long_variable_name,
)
local test = (
        long_variable_name
        + long_variable_name
        + long_variable_name
        + long_variable_name
    )
```

It should look more like this:

```lua
local tbl = {
    key = long_variable_name,
    key = long_variable_name,
    key = long_variable_name,
    key = long_variable_name,
}
function_call(
    long_variable_name,
    long_variable_name,
    long_variable_name,
    long_variable_name,
)
local test = (
    long_variable_name
    + long_variable_name
    + long_variable_name
    + long_variable_name
)
```

**Comment by JohnnyMorganz** [comment]
Ah, I figured out *why* its indented one level further, but that doesn't mean we can't change it:

Basically at an assignment, what we are doing here is hanging the assigned expression. In this case, the expression is a set of additions wrapped around in parentheses.
We add a single further level of indentation because we do this for *all* expressions, e.g.:
```lua
local expr_result = 1
    + 2
    + 3
    + 4
    + 5 --a comment
    + 6
    + 6
    + 8

local instance = someReallyLongConditionExtremelyLongSoLongYourMindWillMelt
        and someReallyLongCondition
        and someOtherReallyLongCondition
    or somethingElse
```
If we remove this extra level of indentation, in the above two cases it will turn into
```lua
local expr_result = 1
+ 2
+ 3
+ 4
+ 5 --a comment
+ 6
+ 6
+ 8

local instance = someReallyLongConditionExtremelyLongSoLongYourMindWillMelt
    and someReallyLongCondition
    and someOtherReallyLongCondition
or somethingElse
```
which doesn't look that nice.
Parentheses take a single increase in indentation the same as above, as its handled in the same "hang expression".
The reason it gets *another* indentation is because we then expand out the inner expression of the parentheses - this adds an extra indent level.

We could special case parentheses to not hang here. The only issue I have with it is its a large diff change for a minor style change - need to weigh up the pros and cons

**Comment by JohnnyMorganz** [comment]
Going to plan to fix this inconsistency having thought about it more - it definitely looks much better when everything is aligned the same way
