### ISSUE TITLE
Total line length not taken into account in for loops

### ISSUE THREAD

**Issue by evaera** [JohnnyMorganz/StyLua#322]
I have a for loop with a long initial line. StyLua formats it like this:

```lua
local function system(world)
	for id, model, lasering, transform in world:query(Components.Model, Components.Lasering, Components.Transform, Components.Mothership) do
	end
end
```

If I make the function call longer, StyLua formats it more correctly:

```lua
local function system(world)
	for id, model, lasering, transform in world:query(
		Components.Model,
		Components.Lasering,
		Components.Transform,
		Components.Mothership,
		Components.Mothership
	) do
	end
end
```

But if I add more variables to the loop, it does not do anything:

```lua
local function system(world)
	for id, model, lasering, transform, id, model, lasering, transform, id, model, lasering, transform, id, model, lasering, transform in world:query(Components.Model, Components.Lasering, Components.Transform, Components.Mothership) do
	end
end
```

Ideally, the formatter should probably produce something close to this:

```lua
local function system(world)
	for id, model, lasering, transform,
		id, model, lasering, transform, 
		id, model, lasering, transform, 
		id, model, lasering, transform 
	in
		world:query(
			Components.Model,
			Components.Lasering,
			Components.Transform,
			Components.Mothership,
			Components.Model,
			Components.Lasering,
			Components.Transform,
			Components.Mothership
		)
	do
	end
end
```

**Comment by JohnnyMorganz** [comment]
The initial input is over width, so we seem to be incorrectly calculating the current amount of line width taken up here. [Prettier example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTACgEp8A+TYAHSkxwgCcjIoNMBtASwBMAaTALYRucADb9RAQzRwGnKAHN+MBpNbZGAgLqYIuAO6NR3AHQBHAK6yAnoQDCEAQAdoCGGhMBZYWP4PnrrAeADLSsvJKmP4uUG4eACqq6pp+jjFxXhAwABayaNmcTsSk1LR0mCxoEKJwJqIQCoRUIPAYzcQ0dAC+NF0gvCAQTjCc6MigkgwMEPoACpMIaMggkqL6ktZLAwBGqmAA1nAwAMqSAnDB8nDI2KsyO3uHJ06SYBHIKlYDcALbcNwibihRQWSQKOAAMU0khgI0Uy0kFhgEH6IGyMAEogA6gVWi8wHBjotOCMAG4k6zLMBoLYgeQyBgwWaqBQCSQ3O5wAYAKzQAA9jhEagBFCxZa5IW6ie4gF4MBnLbaSP6iVFOOSwLE8HLIACMACYAAwDdUQGRY1ROZbquAM0nXAaWcXMoZLFDSAC0sX+-1RDDglk4-uZYLZHOlXJAMgEnA+DC+UaFcFF4vDMpgyq13B1SH1AxUkk4ogi-jDKFtAFZURYZPFlW6pTLSVYAJJQESwY5gOTDACC7eOMGsNTTcC6XSAA) for reference

In your ideal case, I think the best we could do is probably split each individual variable on its own line. Splitting every X (in this case 4) variables seems very arbitrary (in this case it works since its 4 variables repeated), so I'm not sure if its the right way to go. Of course, the downside is that it takes up a lot of vertical space sticking each variable on a new line, [but this is the format prettier also uses](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTACgEp8A+TYAHSkxwgCcjIoNMBtTASwBMAaTAFsIPOABsBYgIZo4DLlADmAmAymtsjQQN4DhoiZmmz5SlWo1ad-ISPGSZchcsyr1aTQ23cb++0cdTFzdLLwBdTAhcAHdGMR4AOgBHAFc5AE9CAGEIQQAHaAQYNASAWTtDHPzC2BKAGUDnASqCqCKSgBULDytMFprisogYAAs5NBGuPOJSalo6TBY0CDE4BLEIRUIqEHgMHeIaOgBfGmOQPhAIPJgudGRQKQYGCGiABSeENGQQKTFoqTpb6XABGajAAGs4DAAMpSQRwOoKODIbB-WSg8FQ2F5KRgZzIVRpS5wQQguA8UQ8BpKFJSRRwABiWikMFuSh+UhSMAgFxAIxggjEAHVJntcWA4DCvlxbgA3WXpH5gNDAkAKEwwN5qRSCKSo9FwS4AKzQAA8Yc5VgBFFLDFFINFiDEgXEMEw-EFScliPl5UwwYW8UbIACMACYAAyXf0QWTCtR5H7+uAmOUoy6pe3a67fFAyAC0bQpFL5DDgqS45e19L1BudRpAskEXEJDGJTatcFt9vrLpg3qDPBDSHDlzcXDEziqdZQqYArHyUrIOt6806XXK0gBJKCiWAwsDyG4AQT3MJg6VWfbgx2OQA).

**Comment by evaera** [comment]
> The initial input is over width, so we seem to be incorrectly calculating the current amount of line width taken up here. [Prettier example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTACgEp8A+TYAHSkxwgCcjIoNMBtASwBMAaTALYRucADb9RAQzRwGnKAHN+MBpNbZGAgLqYIuAO6NR3AHQBHAK6yAnoQDCEAQAdoCGGhMBZYWP4PnrrAeADLSsvJKmP4uUG4eACqq6pp+jjFxXhAwABayaNmcTsSk1LR0mCxoEKJwJqIQCoRUIPAYzcQ0dAC+NF0gvCAQTjCc6MigkgwMEPoACpMIaMggkqL6ktZLAwBGqmAA1nAwAMqSAnDB8nDI2KsyO3uHJ06SYBHIKlYDcALbcNwibihRQWSQKOAAMU0khgI0Uy0kFhgEH6IGyMAEogA6gVWi8wHBjotOCMAG4k6zLMBoLYgeQyBgwWaqBQCSQ3O5wAYAKzQAA9jhEagBFCxZa5IW6ie4gF4MBnLbaSP6iVFOOSwLE8HLIACMACYAAwDdUQGRY1ROZbquAM0nXAaWcXMoZLFDSAC0sX+-1RDDglk4-uZYLZHOlXJAMgEnA+DC+UaFcFF4vDMpgyq13B1SH1AxUkk4ogi-jDKFtAFZURYZPFlW6pTLSVYAJJQESwY5gOTDACC7eOMGsNTTcC6XSAA) for reference
> 
> In your ideal case, I think the best we could do is probably split each individual variable on its own line. Splitting every X (in this case 4) variables seems very arbitrary (in this case it works since its 4 variables repeated), so I'm not sure if its the right way to go. Of course, the downside is that it takes up a lot of vertical space sticking each variable on a new line, [but this is the format prettier also uses](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTACgEp8A+TYAHSkxwgCcjIoNMBtTASwBMAaTAFsIPOABsBYgIZo4DLlADmAmAymtsjQQN4DhoiZmmz5SlWo1ad-ISPGSZchcsyr1aTQ23cb++0cdTFzdLLwBdTAhcAHdGMR4AOgBHAFc5AE9CAGEIQQAHaAQYNASAWTtDHPzC2BKAGUDnASqCqCKSgBULDytMFprisogYAAs5NBGuPOJSalo6TBY0CDE4BLEIRUIqEHgMHeIaOgBfGmOQPhAIPJgudGRQKQYGCGiABSeENGQQKTFoqTpb6XABGajAAGs4DAAMpSQRwOoKODIbB-WSg8FQ2F5KRgZzIVRpS5wQQguA8UQ8BpKFJSRRwABiWikMFuSh+UhSMAgFxAIxggjEAHVJntcWA4DCvlxbgA3WXpH5gNDAkAKEwwN5qRSCKSo9FwS4AKzQAA8Yc5VgBFFLDFFINFiDEgXEMEw-EFScliPl5UwwYW8UbIACMACYAAyXf0QWTCtR5H7+uAmOUoy6pe3a67fFAyAC0bQpFL5DDgqS45e19L1BudRpAskEXEJDGJTatcFt9vrLpg3qDPBDSHDlzcXDEziqdZQqYArHyUrIOt6806XXK0gBJKCiWAwsDyG4AQT3MJg6VWfbgx2OQA).

👍 Whatever you think is best
