### ISSUE TITLE
Pre-commit fails due to missing "cargo" executable

### ISSUE THREAD

**Issue by Jarmos-san** [JohnnyMorganz/StyLua#338]
First off, thanks for creating Stylua, it's a great project & has been very helpful for me.

I use [pre-commit](https://pre-commit.com) on a daily basis & was glad to find out Stylua has support for it as well. Unfortunately, it appears I need to have [Cargo](https://github.com/rust-lang/cargo) installed to use the Pre-commit hook as well.

So, I was wondering if it was possible to use the Stylua binary (which should be available on `$PATH`) instead of building it from scratch? Or implement a condition wherein the binary will be built only when it doesn't exit in `$PATH`?

All in all, it doesn't sound right to obligate the user to install Cargo as well just to use Stylua as a pre-commit hook.

**Comment by JohnnyMorganz** [comment]
Hey, great to hear StyLua is working for you!

The default precommit hook is based on the rust tool chain, but some contributors have also added options for a system hook (#331) and an autoinstaller python hook (#336)

Maybe one of those PR implementations can help you (I think for the system implementation - which is the one you want - you can use the `stylua-system` hook rather than the base `stylua` one). Hope that helps!

The README should probably also be updated to talk about all 3 precommit hook variants

**Comment by Jarmos-san** [comment]
> The default precommit hook is based on the rust tool chain, but some contributors have also added options for a system hook (#331) and an autoinstaller python hook (#336)

Sounds promising!

It also appears, the latest release missed these contributions? Any clue when will you be releasing the next version with these patches? I'll be looking forward to it since I still haven't been able to set it up properly yet. So, a README with the instructions laid out nicely will be VERY helpful.

**Comment by JohnnyMorganz** [comment]
> Any clue when will you be releasing the next version with these patches? I'll be looking forward to it since I still haven't been able to set it up properly yet. So, a README with the instructions laid out nicely will be VERY helpful.

I plan on the next release being out once #289 and #292 are sorted. For the time being though, I think you can use `rev: master` in your pre commit config to use it immediately

**Comment by Jarmos-san** [comment]
Closing the thread then since it's an non-issue as long as the latest revision of the hook is used.
