### ISSUE TITLE
README: the Sublime package is not really another installation method

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [JohnnyMorganz/StyLua#393]
The README lists a Sublime Text package as an alternative installation method. Yet, the package in question, in [_its_ installation instructions](https://github.com/aerobounce/Sublime-Pretty-Lua), says to install . . your program. So the Sublime Package is not a way to install your program; rather, installing the SublimePackage presupposes that your program is installed.

(Also, the package in question is not yet installable via SublimeText's Package Control.)

EDITED to fix a typo.

**Comment by JohnnyMorganz** [comment]
This is a good point.

@aerobounce do you reckon you could make it so the sublime extension automatically installs stylua, like the vscode extension does?

**Comment by aerobounce** [comment]
I agree that the package is not an "Installation method", but is a plugin.
For automatic binary download, unfortunately I'm not considering it because:

1. StyLua is available on variety of package managers.
2. I'd like my packages to be separated from its dependencies and would like users to manage it.

Regarding its availability on PackageControl.io, as it is mentioned in README, [PR is already opened](https://github.com/wbond/package_control_channel/pull/8475). However, when it will be merged is... nobody knows except its maintainer. I'm guessing it'll take a while.

That said, in case if you feel my package doesn't fit, please don't hesitate to remove it.

**Comment by LinuxOnTheDesktop** [comment]
Why not have the extra heading 'Sublime Text Plugin', or perhaps just 'Plugins', and link to [Sublime-Pretty-Lua](https://github.com/aerobounce/Sublime-Pretty-Lua) under that heading?

(For: it is useful to know about the plugin; it should not be suggested, falsely, that installing the plugin installs styLua; and making it the case that installing the plugin installs styLua is off the table.)
