### ISSUE TITLE
if... then ... else statements not aligned when wrapped and indented

### ISSUE THREAD

**Issue by KyleMit** [JohnnyMorganz/StyLua#43]
### Input

```lua
local myObj = {
	myProp = function(reallyLongVariableNameEatsUpSpace)
		if
			reallyLongVariableNameEatsUpSpace == "foo"
			or reallyLongVariableNameEatsUpSpace == "bar"
			or reallyLongVariableNameEatsUpSpace == "baz"
		then
			return "hello"
		end
	end,
}
```

### Output

```lua
local myObj = {
	myProp = function(reallyLongVariableNameEatsUpSpace)
		if
			reallyLongVariableNameEatsUpSpace == "foo"
			or reallyLongVariableNameEatsUpSpace == "bar"
			or reallyLongVariableNameEatsUpSpace == "baz"
	then
			return "hello"
		end
	end,
}
```

### Expected Behavior

The `then` statement should be aligned with the corresponding `if` ... `end` blocks

```diff
- 	then
+ 		then
```

**PS**: This project is amazing and solving so many issues - hope my edge case detection / bug reporting is helpful, but very grateful to have 95%+ of our formatting auto solved.

**Comment by JohnnyMorganz** [comment]
Hi @KyleMit, this issue was actually already reported in #32, but thank you for the report nonetheless!. I have pushed a fixed to master, but I haven't released a new version yet - I was hoping in trying to get most/all the current bug reports fixed before a new version was released.

If its a big problem, at the moment I would recommend cloning the master branch and building locally (if you're using the VSCode extension, you can drop in the new binary at `stylua.styluaPath`). However, if I don't get all the current open issues done soon, I'm happy to push for a new release if necessary.

Thank you for your kind words too! I definitely do appreciate your bug reports. StyLua is still in its infancy, and hopefully it will mature enough so that bugs become more rare 🙂.
