### ISSUE TITLE
intersection and union operators should follow same style guide as `..` and `+`

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#447]
looking at this diff:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1550766/164945321-c065a96b-e7f9-48a3-b9f6-1d77e5f06506.png">

The Roblox Lua style guide talks about hanging `..` and `+` chains as a prefix to prevent unnecessary diff noise when adding/removing from the chain. It seems like any binary operator, including `|` and `&` in type definitions, should do the same.

**Comment by JohnnyMorganz** [comment]
This is a tricky one, because this is under the column width so it technically passes.
A fully expanded version for reference:
```lua
export type Visitor<KindToNode, Nodes = any> =
	EnterLeave<
		VisitFn<Nodes>
		| ShapeMap<KindToNode, <Node>(Node) -> VisitFn<Nodes, Node>>
	>
	| ShapeMap<
		KindToNode,
		<Node>(Node) -> VisitFn<Nodes, Node>
			| EnterLeave<VisitFn<Nodes, Node>>
	>
```
We can see that in the top level it is actually just two type unions as in the formatted version (the original looked like 4), but I agree that the generics inside of it are difficult to parse.

**Comment by JohnnyMorganz** [comment]
@matthargett Given that you changed the style guide to use 100 column width now, is this still an issue?
I just tested it locally and it produces the nicer output when using 100 columns.

I don't think there's much we can do for the 120 column output since its technically correct and changing it is difficult as there aren't any nice heuristics

**Comment by matthargett** [comment]
agreed. thanks!
