### ISSUE TITLE
VSC formatOnType support

### ISSUE THREAD

**Issue by Barocena** [JohnnyMorganz/StyLua#462]
Currently, VSC extension is not supporting `editor.formatOnType` setting

would be cool if it it's possible

**Comment by LastTalon** [comment]
This is a really good goal, but is also hard at the moment because stylua's parsing isn't error tolerant or incremental. Which means it would be both slow because it would need to format the whole file at a minimum every time you typed a single character, and it would also fail to format the majority of the time (until you've produced a valid grammar while typing). The latter could feasibly be hidden from the user to an extent, simply providing no feedback when the grammar isn't valid.

To do this well, overall, I think there need to be updates to our parsing library (full moon) to support incremental parsing and error tolerant parsing, as well as to stylua to support these features. Those would enable the extension to format seamlessly as you type similar to Prettier.

**Comment by JohnnyMorganz** [comment]
Unfortunately, with our current parsing, this doesn't seem feasible to do in any useful capacity, as whilst typing the likelihood of parse errors is very high.
Even if we did have an error tolerant parser, I'm not sure its worthwhile running a formatter on code with parse errors - error tolerance doesn't necessarily imply all the AST fragments are completely correct, it wholly depends on current context, and what a user might be typing next may change the AST structure completely - prematurely formatting would lead to undesirable behaviour.

I'm going to close this as a wontfix, as I don't think it is worthwhile to do
