### ISSUE TITLE
Maintain `do` block formatting

### ISSUE THREAD

**Issue by Mullets-Gavin** [JohnnyMorganz/StyLua#55]
`do` blocks get moved down from their original starting line, which should not occur if it causes no issues.

What I wrote:
```lua
local thing = {} do
	thing.__index = thing

	function thing.new()
		return setmetatable({ key = "hi" }, thing)
	end

	function thing:method()
		print(self.key)
	end
end
```

What's formatted:
```lua
local thing = {}
do
	thing.__index = thing

	function thing.new()
		return setmetatable({ key = "hi" }, thing)
	end

	function thing:method()
		print(self.key)
	end
end
```

The `do` should **not** move below the line.

**Comment by LastTalon** [comment]
Which types of expression should have a do block inlined?

**Comment by JohnnyMorganz** [comment]
I'm not entirely sure about this, as I seem to remember that I did this for a specific reason, but the reason has escaped me for now. I'll get back to you

**Comment by Mullets-Gavin** [comment]
@LastTalon mostly for classes and tables, I occasionally do this for initializing something at the top of my script, and the classes formatting is a common pattern within Roblox CoreScripts and other open source code like [dumpster](https://gist.github.com/Fraktality/f0ab4ad950698e9f08bb01bea486845e) follow this design.

Since `do` blocks are rarely used, I would prefer them inline with how I wrote a specific code block to "initialize" the variable/table/class etc.

**Comment by LastTalon** [comment]
I'm just concerned because I think that the formatter should remain consistent in whether it inlines the do blocks or doesn't. So if there's a particular pattern then it should always inline it for that pattern, but I can think of lots of expressions where it clearly should not be doing it when they precede it.

**Comment by Mullets-Gavin** [comment]
If i'm putting it in-line, the do block should respect the inline, if i'm not, then format the original way. In most cases you rarely use do blocks alone, so it should respect the in-line format pattern for those cases.

**Comment by LastTalon** [comment]
Ideally the formatter should produce the same formatting regardless of the way it was originally written though. We should defer to the original formatting sparingly.

**Comment by LastTalon** [comment]
To clarify what I meant:

We should prefer the formatter do the formatting. If the formatter prefers inline `do` statements in some cases it should seek to transform non-inline `do`s into inline ones as well.

To determine when to inline and when not to inline we should be able to clearly state the case when it happens rather than relying on the programmer to reveal this intention and have the formatter do nothing.

We should have
```lua
local thing = {}
do
```
become
```lua
local thing = {} do
```
as well.

I think that inline `do` is an idiom worth preserving, I'm just concerned that we don't inline inappropriately as well. Its possibly the case that we desire inline `do` when its preceded by assignment. Could someone help verify this?

Apologies for not being so clear originally.

**Comment by JohnnyMorganz** [comment]
I'm still not 100% sure about this, but I'll think about it.

Even if I did go down this route, doing so will be quite difficult. Currently, StyLua treats each statement within the AST individually, and formats them - including adding the trailing new line or the leading indent. The new line is added at the end of the LocalAssignment node, and indent is added to the start of the DoBlock node, and they both have no access to each other (i.e. the LocalAssignment doesn't know that a do block is next). Therefore, it is currently impossible for the LocalAssignment to decide not to add a new line at the end, and same with the indent in the DoBlock.

There is probably a way to work with this, and I'll see how it goes.

**Comment by JohnnyMorganz** [comment]
I've decided that it is unlikely that I will be doing this anytime soon. I feel as though this style point is minor, but the decisions need to be made around it, and the implementation, are quite large. I may come back to it some time in the future, but I don't think it is worth the hassle currently.
