### ISSUE TITLE
Inline parameter comments may be wrapped to wrong line

### ISSUE THREAD

**Issue by tonycuadra** [JohnnyMorganz/StyLua#561]
For example, this:
```lua
self:doTheThing(what, --[[rightAway = ]] true)
```

Is rewritten by Stylua to:
```lua
self:doTheThing(
    what, --[[rightAway = ]]
    true
)
```

It would be preferable to distinguish these short inline parameter comments and not wrap at all.

**Comment by JohnnyMorganz** [comment]
I was just thinking the exact same thing in https://github.com/JohnnyMorganz/StyLua/issues/543 and tried implementing it, but it caused some negative regressions for other repos shown in https://github.com/JohnnyMorganz/StyLua/pull/549, so I decided against it.

If you have a better rule to apply I'm more than happy to look into it, but it's unfortunate that we cannot do this as-is. (Ideally the comments should've been single line comments in the offending repos, and this would be fine, but that's not something we can control, and I imagine there are other repos which do this too)

**Comment by JohnnyMorganz** [comment]
Coming back to this, I just realised the diffs in https://github.com/JohnnyMorganz/StyLua/pull/549#issuecomment-1221546802 are actually incorrect. These are applied after initially formatting stylua using main branch, then using the PR changes.

It actually won't be as bad as that, since looking at the original code it was already inlined. We should be able to do this

**Comment by JohnnyMorganz** [comment]
I've fixed the large scale testing diffs, and it shows that this isn't actually a bad change: https://github.com/JohnnyMorganz/StyLua/pull/549#issuecomment-1236108188

I think its reasonable to add this in #549 

cc @matthargett

**Comment by tonycuadra** [comment]
Excellent! Thanks
