### ISSUE TITLE
Literal Call Syntax

### ISSUE THREAD

**Issue by tjdevries** [JohnnyMorganz/StyLua#65]
Hey, awesome project :)

I was wondering if there was any way that functions called with literals & one argument could be kept without parenths? I know you're going for very opinionated code formatter, so I understand (and generally quite like this -- I've used `black` before and it was a plasure) but am wondering if is possible to either not add the parenths.

We often use the table literal constructor to simulate keyword args in some projects I work on, and I've been finding it quite pretty to leave them as the function literal call.

Anyway, cool project and hope you have a good day :)

**Comment by JohnnyMorganz** [comment]
Hey there, thanks for your interest!

I'm not entirely sure about leaving parentheses removed. The [style guide we follow](https://roblox.github.io/lua-style-guide/#functions) recommends against this, with the reasoning that it's harder to parse, and consistency in the whole codebase. It's also mentioned a little in the [LuaRocks Style Guide](https://github.com/luarocks/lua-style-guide#function-calls), however you mentioned that your case was about tables rather than string literals, and they say it's OK to do so sometimes.

I'm hesitant about adding a configuration option, as I don't really want to add too many. Our goal is also to try and provide a single consistent style as much as possible, and configuration goes against that.

I can think about it, but personally right now I think it's unlikely to happen unfortunately. But if you have anything further you want to say, I'm happy to hear about it!

**Comment by tjdevries** [comment]
Yeah, I understand the desire to not have too many configuration options and saw that you mentioned it in other issues.

I'll make my pitch, which you can disregard completely :)

1. I think many style recommendations for Lua are built around the idea that there exists no way to automatically format Lua ( until now! :wink: )
    - Consider instead `golang`, which has `gofmt` line up all the `=`, type definitions, etc.
    - These kinds of problems can be solved with an auto-formatter in a way that creates a consistent code style for your code base even accounting for these rules.
2. For many cases in Neovim (where I'm writing a lot of Lua these days) we're trying to make code feel very ergonomic and builtin, similar to how people can configure things in vimscript.

For example:

```vim
nnoremap <space>dn :lua vim.lsp.diagnostic.goto_next()<CR>
```

And correspondingly in Lua

```lua
vim.nnoremap { "<space>dn", vim.lsp.diagnostic.goto_next }
```

I find that much prettier than

```lua
vim.nnoremap({ "<space>dn", vim.lsp.diagnostic.goto_next})
```

Of course, that is just personal preference, but many other people use this similar style within Neovim.

Additionally, we have alot of cases like this:

```lua
local j = Job:new {
  command = "ls"
  args = { "-al" },
}
```

where I find the initialization is much prettier without bonus parenths.

Ultimately, it's your choice of course :) I just find this part of Lua's syntax allows for feeling like you can use keyword arguments and it makes it clear the style of argument you're doing. In my project https://github.com/nvim-telescope/telescope.nvim we use this pattern almost everywhere because we use an `opts` table to pass around many different keyword args to different functions. This makes it clear there are not and will not be other arguments added. Everything must be in the `opts` table.

Not sure I explained myself great, but there's a wall of text :laughing:

**Comment by JohnnyMorganz** [comment]
I very much appreciate the reply, thank you for your insight! I'll have a think about it, however I cannot promise anything. I understand how it is particularly challenging to uproot an existing style in a large codebase, and it will definitely lead to differing opinions.

**Comment by tjdevries** [comment]
Well it's quite easy with the `stylua`, I ran it over the codebase and liked effectively everything excluding this -- so I'll just have to decide what we want to do there :laughing: 

Very cool project :+1:

**Comment by lucastrvsn** [comment]
I'm using prettier for about 4 years and I really like how little options for configuration it has and still have a consistent style. Maybe add some configuration file like prettier does (.prettierrc) would be awesome and, in my opinion, will continue to  have the consistency. I really think it's for options like this: minor developer preference with no impact in the whole code style. Like, in prettier, we can choose to have parentheses in arrow functions with one arguments or not. It's a minor preference which not impact the whole style.

Thanks for your project, loving every bit of it!

**Comment by LastTalon** [comment]
Just throwing my opinion on the issue, that I've brought up on other issues. I think its the job of the formatter to make these sorts of decisions rather than letting the programmer hint/dictate the format. This is the exact kind of disagreement about style that is the reason we want to use a formatter.

I actually agree that in some cases that style of function call can be useful, which actually differs from the opinion of some of my peers. But I see no way to reconcile using this style over the more general case without simply leaving it up to the programmer to decide the style and have the formatter do nothing for these sections of code.

We should prefer that the formatter produce the same styled for code regardless of the style given for the input originally. That's its job, to ensure the code is given the same consistent style regardless of how the programmer styles it.

**Comment by tjdevries** [comment]
(sorry for short reply, on mobile)

My point is that you could produce the same output every time with this setting. 

Any one argument function call that takes a table constructor would have its parentheses removed. That's actually what I want in my current project. 

Perhaps some kinds of literal strings could also be added, but I my main focus would be table constructors.

**Comment by JohnnyMorganz** [comment]
> I'm using prettier for about 4 years and I really like how little options for configuration it has and still have a consistent style. Maybe add some configuration file like prettier does (.prettierrc) would be awesome and, in my opinion, will continue to  have the consistency. I really think it's for options like this: minor developer preference with no impact in the whole code style. Like, in prettier, we can choose to have parentheses in arrow functions with one arguments or not. It's a minor preference which not impact the whole style.

@lucastrvsn
Thank you for your thoughts! You mentioned prettier and I think the `--arrow-parens` option. In their Option Philosphy documentation (https://prettier.io/docs/en/option-philosophy.html), they state the following:
"But other options are harder to motivate in hindsight: `--arrow-parens`, [...] are not the type of options we’re happy to have. They cause a lot of bike-shedding in teams, and we’re sorry for that. Difficult to remove now, these options exist as a historical artifact and should not motivate adding more options (“If those options exist, why can’t this one?”)."

This is the dilemma which I face right now, and I'll continue to think about it. It would be great if this project reaches a bigger audience, but I don't know whether adding the configuration is something I will regret later

**Comment by lucastrvsn** [comment]
> > I'm using prettier for about 4 years and I really like how little options for configuration it has and still have a consistent style. Maybe add some configuration file like prettier does (.prettierrc) would be awesome and, in my opinion, will continue to  have the consistency. I really think it's for options like this: minor developer preference with no impact in the whole code style. Like, in prettier, we can choose to have parentheses in arrow functions with one arguments or not. It's a minor preference which not impact the whole style.
> 
> @lucastrvsn
> Thank you for your thoughts! You mentioned prettier and I think the `--arrow-parens` option. In their Option Philosphy documentation (https://prettier.io/docs/en/option-philosophy.html), they state the following:
> "But other options are harder to motivate in hindsight: `--arrow-parens`, [...] are not the type of options we’re happy to have. They cause a lot of bike-shedding in teams, and we’re sorry for that. Difficult to remove now, these options exist as a historical artifact and should not motivate adding more options (“If those options exist, why can’t this one?”)."
> 
> This is the dilemma which I face right now, and I'll continue to think about it. It would be great if this project reaches a bigger audience, but I don't know whether adding the configuration is something I will regret later

You are absolutely right! Just leaving our thoughts to make this project even better!

Maybe it's a evil we have to deal with ☺️

Thanks again for all the hard work.

**Comment by JohnnyMorganz** [comment]
Hey @tjdevries (and others), hope you're all doing well. I was wondering what decision you made in regards to adopting StyLua in your codebases, even without the wanted feature described here. I'm *still* thinking (and hesitant) about this, but I'm most likely going to be releasing a new version later this week, so I want to see if I should tackle this issue before that release.

**Comment by tjdevries** [comment]
Hey @JohnnyMorganz , Thanks for following up :)

We decided against using it because I like the `my_func { literal = true }` style too much to lose it :) This is not a dig against the project or anything, it seems very cool and useful for a lot of people.

My mind may change over time to use it regardless, but for now we have passed on it.

Good luck with your release :)

**Comment by JohnnyMorganz** [comment]
Thanks for your reply, and I appreciate you taking an interest nonetheless

I think, ultimately, I am going to go with my gut here, and I won't be adding this in for now. I may, however, rethink this some time in the future, but since I am currently still hesitant about it, I don't think I should do it right now.

Thanks everyone for your thoughts 🙂
