### ISSUE TITLE
doesn't respect `-- stylua: ignore start` when it is in a multiline bracket

### ISSUE THREAD

**Issue by juiceDeLemon** [JohnnyMorganz/StyLua#705]
for example this won't work:
```lua
require("foo").bar {
    -- stylua: ignore start
    baz      =0
    -- stylua: ignore end
}
```
but this won't too
```lua
-- stylua: ignore start
require("foo").bar {
    baz=0, -- <- this will not get formatted
    -- stylua: ignore end
    hello    ="world" -- <- this will not get formatted too because the ignore end is not detected?
}
```

I will not be able to not format something only in that {} bracket

**Comment by JohnnyMorganz** [comment]
For the second code snippet, mutliline ignores do not traverse across different "scopes", i.e., the ignore end must be at the same level as the ignore start. So that is not a bug here.

Technically ignore start/end only work at the statement level, but I think it is valid to support your first code snippet. But again, the ignore start/end will only work within the table fields, so the following snippet won't work

```lua
require("foo").bar {
    -- stylua: ignore start
    baz      =0 -- < this will be ignored
}

local   x      = 1 -- this will get formatted
-- stylua: ignore end
```

**Comment by juiceDeLemon** [comment]
thanks
