### ISSUE TITLE
Formatting breaks IIFE's

### ISSUE THREAD

**Issue by ckipp01** [JohnnyMorganz/StyLua#89]
Hello! Thanks for the great formatter! I've been hungry for a prettier-style Lua formatter.

Given the following snippet:

```lua
local M = {}

M.path = (function()
  local function exists(filename)
    local stat = uv.fs_stat(filename)
    return stat and stat.type or false
  end
  return {
    exists = exists,
  }
end)()

return M
```

This will be formatted like so:

```lua
local M = {}

M.path = function()
	local function exists(filename)
		local stat = uv.fs_stat(filename)
		return stat and stat.type or false
	end
	return {
		exists = exists,
	}
end()

return M
```

Notice the removal of the `()` around the function. This ends up breaking the code. I don't have strong feelings here about _how_ the formatting should be here, but just not have it break the code.

**Comment by JohnnyMorganz** [comment]
Thanks for the report! It may be a few days until I get a new release out though (waiting on an upstream crate to update), but since this is a breaking bug, you may want to build from source now (also assuming you have `cargo` installed).

If you do, you can run:
```
cargo install --git https://github.com/JohnnyMorganz/StyLua
```
or alternatively, you can clone the repo locally and then run `cargo build --release`
